# Build the all in windows/.
# Provide windows for the apps.

all:
# Display server and libraries
	make -C gram3d/

clean:
# Display server and libraries

clean-all:
# Display server and libraries
	-rm gram3d/bin/*.BIN 
